-- =====================================================================
--  베트남 사격연맹 권총기록 아카이브 — Supabase / PostgreSQL 스키마
--  대상: ISSF 권총 전 종목 (10m / 25m / 50m), 국내·국제, 주니어·연령별
--  원본: 베트남 사격연맹 공개 구글시트(CSV) → ETL 적재
--  식별키: 이름 + 출생연도(국내) / 이름 + 국가(국제)
--  등위: ISSF 규정 6.15.1 계산 (원본에 등위 컬럼 없음)
-- =====================================================================

-- 재실행(멱등) 편의를 위해 역순 드롭
drop table if exists series       cascade;
drop table if exists results      cascade;
drop table if exists affiliations cascade;
drop table if exists athletes     cascade;
drop table if exists events       cascade;
drop table if exists competitions cascade;
drop table if exists ingest_runs  cascade;

-- ---------------------------------------------------------------------
-- 적재 이력(감사/증분 갱신 추적)
-- ---------------------------------------------------------------------
create table ingest_runs (
  id           bigint generated by default as identity primary key,
  started_at   timestamptz not null default now(),
  source_url   text,
  source_rows  int,          -- CSV 원본 행 수
  loaded_rows  int,          -- 실제 적재된 결과 행 수
  dropped_rows int,          -- 중복/부분/스케줄로 제외된 행 수
  note         text
);

-- ---------------------------------------------------------------------
-- 대회
-- ---------------------------------------------------------------------
create table competitions (
  id             bigint generated by default as identity primary key,
  year           int  not null,
  name           text not null,
  date_start     date,
  date_end       date,
  location       text,
  scope          text check (scope in ('domestic','international')),
  raw_date_range text,                       -- 원본 "29.06 - 08.07.2026"
  created_at     timestamptz not null default now(),
  unique (year, name)
);
comment on table competitions is '대회 1건 = (연도, 대회명) 유일';

-- ---------------------------------------------------------------------
-- 종목 (대회 내 세부 종목 1건)
--   raw_name 예: "25m Súng ngắn thể thao nữ trẻ"
--   결선(-C.kết) 스케줄 행은 적재하지 않음. 결선점수는 results.final_score 에 보관.
-- ---------------------------------------------------------------------
create table events (
  id             bigint generated by default as identity primary key,
  competition_id bigint not null references competitions(id) on delete cascade,
  raw_name       text   not null,
  distance       text   check (distance in ('10m','25m','50m')),
  -- air=공기, rapid_fire=속사, sport=스포츠(여자권총), standard=표준,
  -- centre_fire=센터파이어(ổ quay), pistol_50=50m권총
  discipline     text   check (discipline in
                    ('air','rapid_fire','sport','standard','centre_fire','pistol_50')),
  gender         text   check (gender in ('M','W','X')),   -- X = 혼성(mixed)
  -- senior / junior(trẻ) / youth(thiếu niên) / u16 / u18
  age_category   text   not null default 'senior',
  team_type      text   check (team_type in ('individual','team','mixed_team')),
  -- 표준 종목코드 예: "AP10M-M-SENIOR", "RFP25M-M-JUNIOR", "AP10M-X-U16-TEAM"
  event_code     text   not null,
  has_final      boolean not null default false,  -- 결선 존재 여부(종목 규정상)
  n_series       int,                              -- 기대 시리즈 수 (30발=3, 60발=6)
  created_at     timestamptz not null default now(),
  unique (competition_id, raw_name)
);
create index on events (event_code);
create index on events (distance, discipline);

-- ---------------------------------------------------------------------
-- 선수 (동일인 통합)
--   식별키 identity_key:
--     국내  = norm(이름)|출생연도|성별
--     국제  = norm(이름)|국가코드|성별   (출생연도 결측 많음)
-- ---------------------------------------------------------------------
create table athletes (
  id           bigint generated by default as identity primary key,
  full_name    text not null,        -- "HỌ TÊN" 결합
  family_name  text,                 -- HỌ
  given_name   text,                 -- TÊN
  birth_year   int,                  -- SINH 또는 ID에서 유도
  birth_date   date,                 -- ID에 YYYYMMDD 있으면 유도
  gender       text check (gender in ('M','W')),
  nationality  text,                 -- 'VN' 또는 국가코드(IND,KOR...)
  is_foreign   boolean not null default false,
  identity_key text not null unique,
  created_at   timestamptz not null default now()
);
create index on athletes (birth_year);
create index on athletes (nationality);
-- 이름 부분검색 (종목+선수명 검색 대응). pg_trgm 있으면 GIN 인덱스 권장.
create index on athletes (lower(full_name));

-- ---------------------------------------------------------------------
-- 소속 이력 (이적·국대겸직으로 소속이 바뀌어도 기록 연결 유지)
-- ---------------------------------------------------------------------
create table affiliations (
  id         bigint generated by default as identity primary key,
  athlete_id bigint not null references athletes(id) on delete cascade,
  unit_code  text   not null,        -- Đ.vị: HCM, CAD, HAP, TQG(국대) ...
  year       int,
  unique (athlete_id, unit_code, year)
);
create index on affiliations (unit_code);

-- ---------------------------------------------------------------------
-- 성적 (선수 × 종목)
-- ---------------------------------------------------------------------
create table results (
  id             bigint generated by default as identity primary key,
  event_id       bigint not null references events(id) on delete cascade,
  athlete_id     bigint references athletes(id) on delete set null,
  unit_code      text,               -- 이 성적 당시 소속
  relay          text,               -- Đợt (조)
  firing_point   text,               -- Bệ (사대)
  bib            text,               -- Số (배번)
  match_date     date,               -- 이 경기가 열린 날짜 (Thời gian)
  match_time     text,               -- 이 경기 시각 "09:30"
  qual_total     numeric(6,1),       -- Cộng (본선 총점)
  inner_tens     int,                -- X (이너텐)
  final_score    numeric(6,1),       -- Điểm K (결선 점수; 없으면 null)
  medal          text check (medal in ('gold','silver','bronze')),  -- HC cá nhân (개인 메달)
  team_medal     text check (team_medal in ('gold','silver','bronze')),  -- HC đồng đội (단체 메달)
  team_medal_no  int,                -- 단체 메달 팀원 번호(팀 구분용)
  qual_rank      int,                -- 계산: 본선 순위 (6.15.1)
  final_rank     int,                -- 계산: 결선 진출자 순위
  placement      int,                -- 계산: 종합 등위 (결선자 우선 → 본선순)
  is_dnf         boolean not null default false,  -- 기권/결장/0점
  raw_event_name text,
  created_at     timestamptz not null default now(),
  unique (event_id, athlete_id)
);
create index on results (athlete_id);
create index on results (event_id);
create index on results (medal);

-- ---------------------------------------------------------------------
-- 시리즈별 점수 (10발 단위)
--   본선 시리즈만 존재. 결선 시리즈는 원본에 없음(총점만).
-- ---------------------------------------------------------------------
create table series (
  id         bigint generated by default as identity primary key,
  result_id  bigint not null references results(id) on delete cascade,
  series_no  int    not null,        -- 1..6
  score      numeric(5,1) not null,
  unique (result_id, series_no)
);

-- =====================================================================
--  RLS: 공개(anon) 키로는 읽기만 허용. 적재는 Postgres 직결(비밀번호)로만.
--  → 검색 UI 는 publishable 키로 SELECT 만 가능, 쓰기·삭제는 불가.
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array['competitions','events','athletes','affiliations','results','series'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists public_read on %I', t);
    execute format('create policy public_read on %I for select to anon, authenticated using (true)', t);
    execute format('grant select on %I to anon, authenticated', t);
  end loop;
end $$;

-- =====================================================================
--  검색 편의 뷰: 선수별 전 기록 (종목+선수명 검색 결과 화면용)
-- =====================================================================
create or replace view v_athlete_results as
select
  a.id            as athlete_id,
  a.identity_key,
  a.full_name,
  a.birth_year,
  a.gender,
  a.nationality,
  a.is_foreign,
  c.year,
  c.name          as competition,
  c.date_start,
  c.date_end,
  c.location,
  c.scope,
  e.raw_name      as event,
  e.distance,
  e.discipline,
  e.gender        as event_gender,
  e.age_category,
  e.team_type,
  r.unit_code,
  r.match_date,
  r.match_time,
  r.qual_total,
  r.inner_tens,
  r.final_score,
  r.medal,
  r.qual_rank,
  r.final_rank,
  r.placement,
  r.id            as result_id
from results r
join athletes     a on a.id = r.athlete_id
join events       e on e.id = r.event_id
join competitions c on c.id = e.competition_id;

-- 선수별 시리즈 상세는 series 를 result_id 로 조인해서 조회.

-- 입상실적(메달) 전용 뷰 — 개인·단체 메달 모두, 본선순위·결선순위 포함
create or replace view v_medals as
select
  a.id as athlete_id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign,
  c.year, c.name as competition, c.date_start, c.scope,
  e.raw_name as event, e.distance, e.discipline, e.gender as event_gender, e.age_category, e.team_type,
  r.unit_code, r.match_date, r.match_time, r.medal, r.team_medal,
  coalesce(r.medal, r.team_medal) as any_medal,
  r.placement, r.qual_rank, r.final_rank,
  r.qual_total, r.inner_tens, r.final_score
from results r
join athletes a on a.id = r.athlete_id
join events e on e.id = r.event_id
join competitions c on c.id = e.competition_id
where r.medal is not null or r.team_medal is not null;

-- 종목·연령부 종합 랭킹용 — 선수×세부종목(개인) 평균 본선점수 집계
create or replace view v_event_avg as
select
  a.id as athlete_id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign,
  (select r2.unit_code from results r2
     join events e2 on e2.id = r2.event_id
     join competitions c2 on c2.id = e2.competition_id
   where r2.athlete_id = a.id and c2.scope = 'domestic'
   order by c2.date_start desc nulls last, r2.match_date desc nulls last limit 1) as current_unit,
  e.distance, e.discipline, e.gender as event_gender, e.age_category, e.team_type,
  count(*) filter (where not r.is_dnf and r.qual_total is not null)          as n_games,
  round(avg(r.qual_total) filter (where not r.is_dnf and r.qual_total is not null), 1) as avg_qual,
  max(r.qual_total)  as best_qual,
  max(r.final_score) as best_final,
  count(*) filter (where r.medal is not null) as n_medals
from results r
join athletes a on a.id = r.athlete_id
join events e on e.id = r.event_id
join competitions c on c.id = e.competition_id
where e.team_type = 'individual' and c.scope = 'domestic'   -- 국내 대회만
group by a.id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign,
  e.distance, e.discipline, e.gender, e.age_category, e.team_type;

-- 선수 명단(검색 자동완성용) — 이름·소속·생년월일 표시
create or replace view v_athlete_directory as
select
  a.id, a.identity_key, a.full_name, a.birth_year, a.birth_date, a.gender, a.nationality, a.is_foreign,
  (select string_agg(distinct af.unit_code, ', ' order by af.unit_code)
     from affiliations af where af.athlete_id = a.id) as units,
  (select count(*) from results r where r.athlete_id = a.id) as n_results,
  (select count(*) from results r where r.athlete_id = a.id and r.medal is not null) as n_medals
from athletes a;

-- 종목 랭킹(대회·종목별 순위표) — 화면에서 필터해서 사용
create or replace view v_event_ranking as
select
  c.year, c.name as competition, c.scope,
  e.id as event_id, e.raw_name as event, e.event_code, e.distance, e.discipline, e.age_category, e.team_type,
  r.placement, r.qual_rank, r.final_rank, r.medal, r.team_medal, r.team_medal_no,
  a.id as athlete_id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign, r.unit_code,
  r.match_date, r.match_time,
  r.qual_total, r.inner_tens, r.final_score, r.is_dnf, r.id as result_id
from results r
join athletes a on a.id = r.athlete_id
join events e on e.id = r.event_id
join competitions c on c.id = e.competition_id;

-- 연도별 종목·연령부 집계 (선수 페이지의 '해당 연도 랭킹'용, 국내 개인)
create or replace view v_event_avg_year as
select
  c.year,
  a.id as athlete_id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign,
  (select r2.unit_code from results r2
     join events e2 on e2.id = r2.event_id
     join competitions c2 on c2.id = e2.competition_id
   where r2.athlete_id = a.id and c2.scope = 'domestic'
   order by c2.date_start desc nulls last, r2.match_date desc nulls last limit 1) as current_unit,
  e.distance, e.discipline, e.gender as event_gender, e.age_category,
  count(*) filter (where not r.is_dnf and r.qual_total is not null)          as n_games,
  round(avg(r.qual_total) filter (where not r.is_dnf and r.qual_total is not null), 1) as avg_qual,
  max(r.qual_total)  as best_qual,
  count(*) filter (where r.medal is not null) as n_medals
from results r
join athletes a on a.id = r.athlete_id
join events e on e.id = r.event_id
join competitions c on c.id = e.competition_id
where e.team_type = 'individual' and c.scope = 'domestic'
group by c.year, a.id, a.full_name, a.birth_year, a.gender, a.nationality, a.is_foreign,
  e.distance, e.discipline, e.gender, e.age_category;

-- 종목·성별 선수별 최고 본선점수 (국제 백분위 벤치마크용, 국내+국제 전체)
create or replace view v_event_best as
select
  a.id as athlete_id, a.is_foreign,
  e.discipline, e.gender as event_gender,
  max(r.qual_total) as best_qual
from results r
join athletes a on a.id = r.athlete_id
join events e on e.id = r.event_id
where e.team_type = 'individual' and not r.is_dnf and r.qual_total is not null
group by a.id, a.is_foreign, e.discipline, e.gender;

grant select on v_athlete_results, v_medals, v_athlete_directory, v_event_ranking, v_event_avg, v_event_avg_year, v_event_best to anon, authenticated;
